# this is sample file
development:
  db:
    user: root
    password: password
    host: ''
    name: arxiv_equations
  vars:
    tarballDir: ./tarballs

production:
  db:
    user: bbf7c03aba1c7f
    password: 75dad521
    host: us-cdbr-iron-east-01.cleardb.net
    name: heroku_5e1afc2d1f0d341
  vars:
    tarballDir: /tmp
